@server= http://localhost:2000

#### forgot password
POST {{server}}/v1/auth/forgot-password
Content-Type: application/json

{
    "email": "email@email.com"
}


#### signup
POST {{server}}/v1/auth/signup
Content-Type: application/json

{
    "email": "liqu@email.com",
    "password": "3023abce$d2",
    "firstName": "hero",
    "lastName": "jame",
    "phoneNo": "09066872122",
    "confirmPassword": "3023abce$d2",
    "address": "1, alien solo str",
    "dateOfBirth": "12-02-2019"
}



### Wallet
POST {{server}}/wallets/create
Content-Type: application/json

{
    "User": "abcdefgh",
    "acct_no": "123458960234",
    "currency": "NGN"
}

####
GET {{server}}