FROM node:alpine

# Install Python and build tools
RUN apk add --no-cache python3 py3-pip make g++

WORKDIR /app

COPY package*.json .

RUN npm ci

COPY . .

EXPOSE 3001

RUN npm run build

CMD ["npm", "start"]