version: "3"

name: lucre-auth

services:
  app:
    build: .
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - database
      - redis-cache

  database:
    image: mongo:8.0-noble
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db

  redis-cache:
    image: redis:alpine
    ports: 
      - "6379:6379"

volumes:
  db-data: